name: EAS Dispatch

on:
  repository_dispatch:
    types:
      - eas_workflow
  workflow_dispatch:

jobs:
  acknowledge_dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Show dispatch info
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Repository: ${{ github.repository }}"
          echo "Source workflow: ${{ github.event.client_payload.workflow }}"
          echo "Branch: ${{ github.event.client_payload.branch }}"
          echo "SHA: ${{ github.event.client_payload.sha }}"
